[theme]
base = "light"
primaryColor = "#1E2761"
backgroundColor = "#F8F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0E1440"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
